#!/usr/bin/env bash

# Update the package lists
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create index.html file
sudo echo "Hello world!" > /var/www/html/index.html

# Restart Nginx
sudo service nginx restart
