#!/usr/bin/env bash
# Configure Nginx to a custom HTTP response header

# Update the system
sudo apt update
sudo apt upgrade -y

# Install Nginx
sudo apt install -y nginx

# Configure the custom HTTP response header
sudo tee /etc/nginx/sites-available/default > /dev/null << EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    add_header X-Served-By 58438-web-02;

    location / {
      try_files \$uri \$uri/ =404;
    }

    location ~ /\.ht {
      deny all;
    }
}
EOL

# Restart Nginx
sudo systemctl restart nginx
