#!/usr/bin/env bash
# Configure Nginx to a custom HTTP response header

# Update the system
apt-get update

# Install Nginx
apt-get -y install nginx

# Set custom header
HOSTNAME=$(hostname)
HEADER="\tadd_header X-Served-By $HOSTNAME;\n"
FIND=$(grep "X-Server-by" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
	# Configure the custom HTTP response header
	sed -i "23i $HEADER" /etc/nginx/sites-available/default
fi

# Creates a file index.html page
echo 'Hello World!' > /var/www/html/index.html

# Add redirection page
FIND=$(grep "redirect_me" /etc/nginx/sites-available/default)
STR="\\\n\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com;\n\t}\n"
if [[ -z $FIND ]]; then
	sed -i "42i $STR" /etc/nginx/sites-available/default
fi

# Add 404 page
FIND=$(grep "error_page 404" /etc/nginx/sites-available/default)
ERROR="\\\n\terror_page 404 /custom_404.html;\n"
if [[ -z $FIND ]]; then
	echo "Page not found!" > /var/www/html/custom_404.html
	sed -i "40i $ERROR" /etc/nginx/sites-available/default
fi

# Restart Nginx
sudo systemctl restart nginx

# Test the configuration by querying Nginx
response=$(curl -s http://localhost)

# Check if the response contains "Hello World!"
if [[ $response == *"Hello World!"* ]]; then
	echo "Nginx is configured correctly."
else
	echo "Nginx configuration failed. Please check the installation and configuration."
fi
