#!/usr/bin/env bash
# Install nginx and starts nginx server. If there is a port running on 80 it disables Install

# Install nginx
sudo apt update
sudo apt install -y nginx

# Check if port 80 is in use
port_in_use=$(lsof -i :80)

if [[ -n "$port_in_use" ]]; then
    # Get the process IDs using port 80
    pids=$(lsof -t -i :80)

    # Stop the processes
    for pid in $pids; do
      sudo kill "$pid"
    done
else
  echo "Port 80 is free."
fi

# Verify Nginx Configuration
nginx_config="/etc/nginx/nginx.conf"
if ! grep -q "listen 80;" "$nginx_config"; then
  echo "Updating Nginx configuration..."
  echo "listen 80;" >> "$nginx_config"
fi

# Check Nginx Service Status
if ! systemct is-active --quiet nginx; then
  echo "Starting Nginx service..."
  sudo systemctl start nginx
fi

# Check Firewall Settings
if ! ufw status | grep -q "Nginx HTTP"; then
  echo "Allowing incoming connections on port 80..."
  ufw allow 'Nginx HTTP'
fi

# Check Listening Ports
if ! netstat -tuln | grep -q ":80"; then
  echo "Restarting Nginx service..."
  sudo systemctl restart nginx
fi

# Update Nginx configuration
sed -i 's/#listen 80;/listen 80;/' /etc/nginx/nginx.conf

