#!/usr/bin/env bash
# This script stops the 7-highlander process.

# Find the PID of the process
pid=$(pgrep -f "7-highlander")

# Check if the process if running
if [[ -z "$pid" ]]; then
	echo "Process not found"
	exit 1
fi

# Terminate the process by sending a SIGTERM signal
if ! /bin/kill -s SIGTERM "$pid"; then
	echo "Failed to stop the process"
	exit 1
fi

exit 0
