#!/usr/bin/env bash
# This script displays "Best School" 10 times and displays "Hi" on the 9th loop using a while loop

count=0
while [ $count -lt 10 ]
do
	echo "Best School"
	if [ $count = 8 ]; then
		echo "Hi"
	fi
	count=$((count + 1))
done
