#!/usr/bin/env bash
# This script displays "bad luck" on the 4th loop, "good luck" on the 8th loop else "Best School" using a while loop

count=0
while [ $count -lt 10 ]
do
	if [ $count = 3 ]; then
		echo "bad luck"
	elif [ $count = 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
