#!/usr/bin/env bash

# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Set default incoming policy to deny
ufw default deny incoming

# Allow SSH (port 22)
ufw allow 22/tcp

# Allow HTTPS (port 443)
ufw allow 443/tcp

# Allow HTTP (port 80)
ufw allow 80/tcp

# Enable ufw
ufw enable
