#!/usr/bin/env bash
# This script configures an Ubuntu server with custom DNS resolutions for localhost and facebook.com
# It takes into account Docker's behavior of overwriting /etc/hosts and uses a workaround

# Create a backup of the hosts file
cp /etc/hosts ~/hosts.new

# Update the backup file with the desired DNS resolutions
sed -i 's/^127\.0\.0\.1[[:space:]]\+localhost$/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^157\.240\.11\.35[[:space:]]\+facebook\.com$/8.8.8.8 facebook.com/' ~/hosts.new

# Overwrite the original hosts file with the modified backup file
sudo cp -f ~/hosts.new /etc/hosts

# Remove the backup file
rm ~/hosts.new
