#!/usr/bin/env bash
# Stop the currently running Nginx service
service nginx stop

# Update Nginx configuration to run as "nginx" user
sed -i 's/user\s*nginx;/user nginx;/' /etc/nginx/nginx.conf

# Update Nginx default site configuration to listen on port 8080 and all IPs
sed -i 's/listen\s*80;/listen 8080;/' /etc/nginx/sites-available/default
sed -i 's/listen\s*\[::\]:80;/listen [::]:8080;/' /etc/nginx/sites-available/default

# Start Nginx service with the new configuration
service nginx start
