#!/usr/bin/env bash
# Configuration of local SSH client to a server without typing a password
Host 54.227.128.255
    HostName 54.227.128.255
    User ubuntu
    IdentityFile ~/.ssh/school
    PreferredAuthentication publickey
    PasswordAuthentication no
